language: android

jdk:
	- oraclejdk7

before_install:
	- chmod +x gradlew
<<<<<<< Updated upstream
 
=======

>>>>>>> Stashed changes
android:
	components:
		- build-tools-22.0.1
		- android-22
		- extra-android-m2repository

script: ./gradlew assembleDebug

notifications:
	email: true

sudo: false